### ISSUE TITLE
Acknowledge the Sloan Foundation grant

### ISSUE THREAD

**Issue by egonw** [LaurenDupuis/Scholia_tutorial#2]
@LaurenDupuis, at the bottom of the page, can you plz acknowledge the grant? With this text:

```
Scholia has received funding from the Alfred P. Sloan Foundation under grant number G-2019-11458.
```

The grant number can be linked to this page: https://sloan.org/grant-detail/8961

**Comment by LaurenDupuis** [comment]
Done!
